# Github action to build Jekyll site for a pull request preview
#
#  Built site is pushed to 'gh-pages' branch
#   under directory pr/pr_id/
#

name: Jekyll PR Preview

on:
  pull_request:
    branches: [ master ]

env:
  SRC_DIR: src
  PUBLISH_DIR: gh-pages
  SITE_URL: https://fortran-lang.org

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    # Checkout PR branch into SRC_DIR
    - name: Checkout pr/${{github.event.number}}
      uses: actions/checkout@v2
      with:
        path: ${{env.SRC_DIR}}
    
    # Checkout existing gh-pages branch into PUBLISH_DIR
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        path: ${{env.PUBLISH_DIR}}
        ref: 'gh-pages' 
    
    # Setup Jekyll in SRC_DIR
    - name: Setup Jekyll
      run: |
        cd ${{env.SRC_DIR}}
        sudo gem install bundler
        bundle config path .bundle
        bundle install
    
    # Sets Jekyll output directory using PR id
    - name: Define output directory
      run: echo "::set-env name=BUILD_DIR::pr/${{github.event.number}}"

    # Appends PR-based output directory to Jekyll baseurl variable
    - name: Update Jekyll site config
      run: |
        cd ${{env.SRC_DIR}}
        grep baseurl _config.yml|grep -v "#" |awk -F : '{print $2}' | xargs > base_url
        sed -i '/baseurl:/d' _config.yml
        echo "baseurl: $(cat base_url)/${{env.BUILD_DIR}}" >> _config.yml

    # Run Jekyll build and copy output to PUBLISH_DIR
    - name: Build Jekyll Site
      run: |
        cd ${{env.SRC_DIR}}
        bundle exec jekyll build -d _site/${BUILD_DIR}
        cp -r _site/* ../${{env.PUBLISH_DIR}}/
        touch ../${{env.PUBLISH_DIR}}/.nojekyll

    # Commit and push changes to remote/gh-pages
    - name: Commit and push to gh-pages
      uses: EndBug/add-and-commit@master
      with:
        cwd: ${{env.PUBLISH_DIR}}
        message: "Jekyll build, preview ${{env.BUILD_DIR}} (on:pull_request)"
        ref: 'gh-pages'
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Write comment to PR with preview link
    - name: Comment on PR with preview link
      uses: thollander/actions-comment-pull-request@master
      with:
        message: "This PR has been built with Jekyll and can be previewed at: <${{env.SITE_URL}}/${{env.BUILD_DIR}}/>"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
