# Github action to cleanup a PR preview
#
#  Runs when a pull request comment contains '#delete_preview'
#

name: PR Preview Cleanup

on:
  issue_comment:
    types: [created]

env:
  PUBLISH_DIR: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body,'#delete_preview')
    
    steps:

    # Checkout existing gh-pages branch into PUBLISH_DIR
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        path: ${{env.PUBLISH_DIR}}
        ref: 'gh-pages'

    # Cleanup preview files
    - name: PR Cleanup
      run: |
        cd ${{env.PUBLISH_DIR}}
        rm -rf pr/${{github.event.issue.number}}

    # Commit and push changes to remote/gh-pages
    - name: Commit and push to gh-pages
      uses: EndBug/add-and-commit@master
      with:
        cwd: ${{env.PUBLISH_DIR}}
        message: "Jekyll build, cleanup pr/${{github.event.issue.number}}"
        ref: 'gh-pages'
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # Comment on pull request 
    - name: Comment on pull request
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{github.event.issue.number}}
        body: The preview build for this PR has now been deleted.